
#
# Optional Volumes:
#  - /opt/phabricator/conf - configuration
#  - /var/repo - code repos
#
#
version: '2'
services:
  phabricator:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        PHABRICATOR_COMMIT: a60580166f
        ARCANIST_COMMIT: b3ea439f4d
        LIBPHUTIL_COMMIT: db3667a62f
    ports: ['80:80']
    volumes:
      - ~/.ssh:/root/.ssh
    environment:
      LOCAL_JSON: $PHABRICATOR_LOCAL_JSON
